title: Default Page


options:
  changeStatus: true
  changeTemplate:
    - contact
    - default
    - culture_talents
    - faire_mieux
    - home
    - jeu
    - mentions
    - nous
    - publications
    - secret_sauce
    - secret_sauce_single
    - vous
    - vous_single
    - voyagerz


tabs:
  content:
    icon: text
    label: Content
    columns:
      main:
        width: 1/1
        sections:
          fields:
            type: fields
            fields:
              text:
                type: textarea
                size: huge

  seotab: seo


